# Generated by Django 5.0.6 on 2024-06-12 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_paperinformation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinformation',
            name='key_words',
            field=models.IntegerField(max_length=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
