# Generated by Django 5.0.6 on 2024-06-12 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_paperinformation_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinformation',
            name='key_words',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
