# Generated by Django 5.0.6 on 2024-06-12 05:11

import django.core.validators
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_paperinformation_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinformation',
            name='file',
            field=models.FileField(upload_to='users/sections/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx']), users.utils.validate_file_size]),
        ),
    ]
